// This Pine Script® code is subject to the terms of the Mozilla Public License 2.0 at https://mozilla.org/MPL/2.0/
// © RVD-Projects

import RVD-Projects/Types/3
import RVD-Projects/Functions/2

import TradingView/ta/9
import PineCoders/Time/5
import RVD-Projects/TradeManager/5

// @version=6
// @link RVD-Projects/MyStrategy/1
// @description My Strategy

// # ========================================================================= #
// #                   |   STRATEGY  |
// # ========================================================================= #
strategy(
 title                           = "My Strategy",
 shorttitle                      = "ST-MyStrategy",
 overlay                         =  true,
 behind_chart                    =  true
//  format                          =  ,
//  precision                       =  ,
//  scale                           =  ,
//  pyramiding                      =  ,
//  calc_on_order_fills             =  ,
//  calc_on_every_tick              =  ,
//  max_bars_back                   =  ,
//  backtest_fill_limits_assumption =  ,
//  default_qty_type                =  ,
//  default_qty_value               =  ,
//  initial_capital                 =  ,
//  currency                        =  , 
//  slippage                        =  ,
//  commission_type                 =  , 
//  commission_value                =  ,
//  process_orders_on_close         =  ,
//  close_entries_rule              =  ,
//  margin_long                     =  ,
//  margin_short                    =  ,
//  explicit_plot_zorder            =  ,
//  max_lines_count                 =  ,
//  max_labels_count                =  ,
//  max_boxes_count                 =  ,
//  calc_bars_count                 =  ,
//  risk_free_rate                  =  ,
//  use_bar_magnifier               =  ,
//  fill_orders_on_standard_ohlc    =  ,
//  max_polylines_count             =  ,
//  dynamic_requests                =  ,
 )
// # ========================================================================= #
// #                   |   STRATEGY  |
// # ========================================================================= #

