// This Pine Script® code is subject to the terms of the Mozilla Public License 2.0 at https://mozilla.org/MPL/2.0/
// © RVD-Projects

import RVD-Projects/Types/2

//@version=6
//@description Black Flag Indicator
indicator("BlackFlag", overlay = true)

norm_o = open
norm_h = high
norm_l = low
norm_c = close

ATRFactor = input(5, "ATR Factor", group="BalckFlag")
ATRPeriod = input(28, "ATR Period", group="BalckFlag")
show_fib_entries = input(true, "Show Fib Entries?", group="BalckFlag")
trailType = input.enum(Types.TrailingType.MODIFIED, group="BalckFlag", title="Smooth type:", options=[Types.TrailingType.MODIFIED, Types.TrailingType.LIMITED])

//////// FUNCTIONS //////////////
Wild_ma(_src, _malength) =>
    _wild  = 0.0
    _wild := nz(_wild[1]) + (_src - nz(_wild[1])) / _malength

/////////// TRUE RANGE CALCULATIONS /////////////////
HiLo = math.min(norm_h - norm_l, 1.5 * nz(ta.sma((norm_h - norm_l), ATRPeriod)))

HRef = norm_l<= norm_h[1] ?
 norm_h - norm_c[1] :
 (norm_h - norm_c[1]) - 0.5 * (norm_l- norm_h[1])

LRef = norm_h >= norm_l[1] ?
 norm_c[1] - norm_l:
 (norm_c[1] - norm_l) - 0.5 * (norm_l[1] - norm_h)

trueRange = trailType == Types.TrailingType.MODIFIED ? math.max(HiLo, HRef, LRef) : math.max(norm_h - norm_l, math.abs(norm_h - norm_c[1]), math.abs(norm_l - norm_c[1]))


/////////// TRADE LOGIC ////////////////////////
loss = ATRFactor * Wild_ma(trueRange, ATRPeriod)

Up = norm_c - loss
Dn = norm_c + loss

TrendUp   = Up
TrendDown = Dn
Trend     = 1

TrendUp   := norm_c[1] > TrendUp[1]   ? math.max(Up, TrendUp[1])   : Up
TrendDown := norm_c[1] < TrendDown[1] ? math.min(Dn, TrendDown[1]) : Dn

Trend := norm_c > TrendDown[1] ? 1 : norm_c < TrendUp[1]? -1 : nz(Trend[1],1)
trail = Trend == 1? TrendUp : TrendDown

ex = 0.00
ex := ta.crossover(Trend, 0) ? norm_h : ta.crossunder(Trend, 0) ? norm_l : Trend == 1  ? math.max(ex[1], norm_h) : Trend == -1 ? math.min(ex[1], norm_l) : ex[1]


// //////// PLOT TP and SL /////////////
plot(trail, "Trail", style = plot.style_line, linewidth = 1, color = color.white, trackprice = true, display = display.all)
plot(ex, "Pivot", style = plot.style_circles, linewidth = 1, color = color.white, display = display.all)

////// FIBONACCI LEVELS ///////////
state = Trend == 1 ? "long" : "short"

fib1Level = 61.8
fib2Level = 78.6
fib3Level = 88.6

f1 = ex + (trail - ex) * fib1Level / 100
f2 = ex + (trail - ex) * fib2Level / 100
f3 = ex + (trail - ex) * fib3Level / 100
l100 = trail + 0

Fib1 = plot(f1,  "Fib 1", style = plot.style_line, color = color.black, display = display.pane)
Fib2 = plot(f2,  "Fib 2", style = plot.style_line, color = color.black, display = display.pane)
Fib3 = plot(f3,  "Fib 3", style = plot.style_line, color = color.black, display = display.pane)
L100 = plot(l100, "l100", style = plot.style_line, color = color.black, display = display.none)

fill(Fib1, Fib2, color = state == "long"? color.new(color.green, 85) : state == "short"? color.new(color.red, 85) : na)
fill(Fib2, Fib3, color = state == "long"? color.new(color.green, 80) : state == "short"? color.new(color.red, 80) : na)
fill(Fib3, L100, color = state == "long"? color.new(color.green, 70) : state == "short"? color.new(color.red, 70) : na)

crossF1 = ta.crossunder(norm_c, f1[1])
crossF2 = ta.crossunder(norm_c, f2[1])
crossF3 = ta.crossunder(norm_c, f3[1])

l1 = state[1] == "long" and crossF1
l2 = state[1] == "long" and crossF2
l3 = state[1] == "long" and crossF3
s1 = state[1] == "short" and crossF1
s2 = state[1] == "short" and crossF2
s3 = state[1] == "short" and crossF3

atr = ta.sma(trueRange, 14)

/////////// FIB PLOTS /////////////////.
// plotshape(show_fib_entries and l1 ? low - atr : na, "LS1", style = shape.triangleup, location = location.belowbar, color = color.black, size = size.small, display = display.pane)
// plotshape(show_fib_entries and l2 ? low - 1.5 * atr : na, "LS2", style = shape.triangleup, location = location.belowbar, color = color.black, size = size.small, display = display.pane)
plotshape(show_fib_entries and l3 ? low - 2 * atr : na, "LS3", style = shape.triangleup, location = location.belowbar, color = color.lime, size = size.small, display = display.pane)
// plotshape(show_fib_entries and s1 ? high + atr : na, "SS1", style = shape.triangledown, location = location.abovebar, color = color.black, size = size.small, display = display.pane)
// plotshape(show_fib_entries and s2 ? high + 1.5 * atr : na, "SS2", style = shape.triangledown, location = location.abovebar, color = color.black, size = size.small, display = display.pane)
plotshape(show_fib_entries and s3 ? high + 2 * atr : na, "SS3", style = shape.triangledown, location = location.abovebar, color = color.yellow, size = size.small, display = display.pane)

//////////// FIB ALERTS /////////////////////
alertcondition(l1, title = "cross over Fib1",  message = "Price crossed below Fib1 level in long trend")
alertcondition(l2, title = "cross over Fib2",  message = "Price crossed below Fib2 level in long trend")
alertcondition(l3, title = "cross over Fib3",  message = "Price crossed below Fib3 level in long trend")
alertcondition(s1, title = "cross under Fib1", message = "Price crossed above Fib1 level in short trend")
alertcondition(s2, title = "cross under Fib2", message = "Price crossed above Fib2 level in short trend")
alertcondition(s3, title = "cross under Fib3", message = "Price crossed above Fib3 level in short trend")
alertcondition(fixnan(f1)!=fixnan(f1[1]), title = "Stop Line Change", message = "Stop Line Change")
